apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeburguer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  zeburguer
  template:
    metadata:
      labels:
        app: zeburguer
    spec:
      containers:
        - name: zeburguer
          image: marcosilva/ze_burguer:latest
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: zeburguer
          - secretRef:
              name: zeburguer
---
apiVersion: v1
kind: Service
metadata:
  name: zeburguer
spec:
  type: NodePort
  selector:
    app: zeburguer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zeburguer
data:
  DATABASE_HOST: "postgres.tech-challenge"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "ze_burguer"
  DATABASE_SCHEMA: "ze_burguer"
  DATABASE_USERNAME: "postgres"
  MIGRATIONS_DIR: "infra/database/migrations"
---
apiVersion: v1
kind: Secret
metadata:
  name: zeburguer
type: Opaque
data:
  DATABASE_PASSWORD: bXlzZWNyZXQxMjMK