version: '3.9'

include:
  - "docker-compose-network.yaml"

services:
  prod-app-orders:
    container_name: app.ze-burger-orders.prod
    env_file: .env
    build:
      dockerfile: ./infra/docker/prod/Dockerfile
      context: .
    ports:
      - 8081:8081
    depends_on:
      orders-postgres:
        condition: service_healthy
    networks:
      - dev-networks

  prod-app-payment-canceled-worker:
    container_name: worker.ze-burger-orders-payment-canceled.prod
    env_file: .env
    command: [ "./cmd/worker/rollback_payment/main" ]
    build:
      dockerfile: ./infra/docker/prod/Dockerfile
      context: ./
    networks:
      - dev-networks

  prod-app-order-status-update-worker:
    container_name: worker.ze-burger-orders-order-status-update.prod
    env_file: .env
    command: [ "./cmd/worker/update_order_status/main" ]
    build:
      dockerfile: ./infra/docker/prod/Dockerfile
      context: ./
    networks:
      - dev-networks
