version: '3.9'

include:
  - "docker-compose-network.yaml"

services:
  orders-localstack:
    image: localstack/localstack:latest
    container_name: orders-localstack
    environment:
      - SERVICES=sqs,sns,dynamodb
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - dev-networks

  orders-aws-cli:
    image: amazon/aws-cli
    container_name: orders-aws-cli
    depends_on:
      - orders-localstack
    env_file: .env
    entrypoint:
      - sh
      - -c
      - |
        sleep 5
        aws --endpoint-url=http://orders-localstack:4566 sns create-topic --name order_status_updated-topic --region us-east-1 --output table | cat
        aws --endpoint-url=http://orders-localstack:4566 sns create-topic --name payment_status_updated-topic --region us-east-1 --output table | cat
        aws --endpoint-url=http://orders-localstack:4566 sns create-topic --name order_created-topic --region us-east-1 --output table | cat
        aws --endpoint-url=http://orders-localstack:4566 sqs create-queue --queue-name order_status_updated-queue --region us-east-1 --output table | cat
        aws --endpoint-url=http://orders-localstack:4566 sqs create-queue --queue-name order_payment_status-updated-queue --region us-east-1 --output table | cat
        aws --endpoint-url=http://orders-localstack:4566 sqs list-queues --region us-east-1 --output table | cat
        aws --endpoint-url=http://orders-localstack:4566 sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:order_status_updated-topic --protocol sqs --notification-endpoint arn:aws:sqs:us-east-1:000000000000:order_status-updated-queue --region us-east-1 --output table | cat
        aws --endpoint-url=http://orders-localstack:4566 sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:payment_status_updated-topic --protocol sqs --notification-endpoint arn:aws:sqs:us-east-1:000000000000:order_payment_status_updated-queue --region us-east-1 --output table | cat
    networks:
      - dev-networks

  orders-postgres:
    container_name: postgres.ze-burguer-orders.dev
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - postgres_data:/data/postgres
    ports:
      - 5432:5432
    networks:
      - dev-networks
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
