services:
  # mysql:
  #   image: mysql
  #   container_name: mysql
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_USER=tech-fiap
  #     - MYSQL_PASSWORD=mysecret123
  #     - MYSQL_DATABASE=ze_burguer
  #     - MYSQL_ROOT_PASSWORD=mysecret123
  #   networks:
  #     - fullstack
  
  app-ze-burguer:
    build:
      dockerfile: ./infra/prod/Dockerfile
      context: .
    container_name: app-ze-burguer
    ports:
      - 8080:8080
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
  