version: '3.9'

include:
  - "docker-compose-network.yaml"

services:
  prod-app-orders:
    container_name: app.ze-burger-orders.prod
    env_file: .env
    build:
      dockerfile: ./infra/docker/prod/Dockerfile
      context: .
    ports:
      - 8081:8081
    depends_on:
      orders-postgres:
        condition: service_healthy
    networks:
      - dev-networks
