version: '3.9'

include:
  - "docker-compose-network.yaml"

services:
  dev-app-orders:
    container_name: app.ze-burger-orders.dev
    env_file: .env
    build:
      dockerfile: ./infra/docker/local/Dockerfile
      context: ./
    volumes:
      - .:/app
    ports:
      - 8080:8080
    networks:
      - dev-networks

  dev-app-payment-status-update-worker:
    container_name: worker.ze-burger-orders-payment-status-update.dev
    env_file: .env
    command: >
      sh -c "go run cmd/worker/update_payment_status/main.go"
    build:
      dockerfile: ./infra/docker/local/Dockerfile
      context: ./
    volumes:
      - .:/app
    networks:
      - dev-networks

  dev-app-order-status-update-worker:
    container_name: worker.ze-burger-orders-order-status-update.dev
    env_file: .env
    command: >
      sh -c "go run cmd/worker/update_order_status/main.go"
    build:
      dockerfile: ./infra/docker/local/Dockerfile
      context: ./
    volumes:
      - .:/app
    networks:
      - dev-networks
