version: '3.9'

include:
  - "docker-compose-network.yaml"

services:
  dev-app-orders:
    container_name: app.ze-burger-orders.dev
    env_file: .env
    build:
      dockerfile: ./infra/docker/local/Dockerfile
      context: ./
    volumes:
      - .:/app
    ports:
      - 8081:8081
    networks:
      - dev-networks
