services:
  postgres:
    container_name: postgres.ze-burguer
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fullstack
  app-ze-burguer:
    build:
      dockerfile: ./infra/prod/Dockerfile
      context: .
    image: golang
    env_file: .env
    container_name: app-ze-burguer
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fullstack


volumes:
  postgres_data:

networks:
  fullstack:
    driver: bridge
  