version: '3.9'

services:
  dev-app:
    container_name: app.ze-burger.dev
    env_file: .env
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - .:/app
    ports:
      - 8080:8080

  postgres:
    container_name: postgres.ze-burguer.dev
    image: postgres:latest
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      PGDATA: /data/postgres
    volumes:
    - postgres_data:/data/postgres
    ports:
      - 5432:5432

volumes:
  postgres_data:
