definitions:
  output.ClientDto:
    properties:
      cpf:
        type: integer
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /clients/{id}:
    get:
      consumes:
      - application/json
      description: Get client by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      - description: Api key
        in: header
        name: apiKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/output.ClientDto'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Show client details
      tags:
      - Clients
swagger: "2.0"
